### ISSUE TITLE
Change fingerprint-light on MI 9 back to green

### ISSUE THREAD

**Issue by nspsck** [PixelOS-Devices-old/device_xiaomi_cepheus#3]
Hi,

Could you please change the lighting of the fingerprint sensor to be green again? I am having issues with the fingerprint detection rate, it's definitively lower than 30%. Since I just flashed PixelOS yesterday and the sensor worked perfectly fine on the previous OS and it worked occasionally on the PixelOS, I concluded that this might happen due to lighting. Maybe the detection is optimized for the greenlight, causing the sensor to have trouble with white light.

Best Regards

**Comment by lori28167** [comment]
It's not the color because I already tried and it works same as the green one. It's a optic sensor so color doesn't take this to happen. If you want you can try changing the fingerprint sensor (It's really hard): https://rounded.com/xiaomi-mi-9-m1902f1g-fingerprint-sensor-492222007076.html?sl=en. Or just edit the code and put the fingerprint screen color to green and then recompile it: https://github.com/shantanu-sarkar/CustomROM (Linux needed)

**Comment by nspsck** [comment]
Thank you very much for your time! In that case, it's probably just on my hardware side.
